// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: kademlia.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_kademlia_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_kademlia_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            []byte                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	IP            string                 `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=Port,proto3" json:"Port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_kademlia_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_kademlia_proto_rawDescGZIP(), []int{1}
}

func (x *NodeInfo) GetID() []byte {
	if x != nil {
		return x.ID
	}
	return nil
}

func (x *NodeInfo) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *NodeInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Init          int64                  `protobuf:"varint,1,opt,name=Init,proto3" json:"Init,omitempty"`
	End           int64                  `protobuf:"varint,2,opt,name=End,proto3" json:"End,omitempty"`
	Buffer        []byte                 `protobuf:"bytes,3,opt,name=Buffer,proto3" json:"Buffer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_kademlia_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_kademlia_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetInit() int64 {
	if x != nil {
		return x.Init
	}
	return 0
}

func (x *Data) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *Data) GetBuffer() []byte {
	if x != nil {
		return x.Buffer
	}
	return nil
}

type StoreData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sender        *NodeInfo              `protobuf:"bytes,1,opt,name=Sender,proto3" json:"Sender,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Value         *Data                  `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreData) Reset() {
	*x = StoreData{}
	mi := &file_kademlia_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreData) ProtoMessage() {}

func (x *StoreData) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreData.ProtoReflect.Descriptor instead.
func (*StoreData) Descriptor() ([]byte, []int) {
	return file_kademlia_proto_rawDescGZIP(), []int{3}
}

func (x *StoreData) GetSender() *NodeInfo {
	if x != nil {
		return x.Sender
	}
	return nil
}

func (x *StoreData) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *StoreData) GetValue() *Data {
	if x != nil {
		return x.Value
	}
	return nil
}

type Target struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            []byte                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Init          int64                  `protobuf:"varint,2,opt,name=Init,proto3" json:"Init,omitempty"`
	End           int64                  `protobuf:"varint,3,opt,name=End,proto3" json:"End,omitempty"`
	Sender        *NodeInfo              `protobuf:"bytes,4,opt,name=Sender,proto3" json:"Sender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_kademlia_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_kademlia_proto_rawDescGZIP(), []int{4}
}

func (x *Target) GetID() []byte {
	if x != nil {
		return x.ID
	}
	return nil
}

func (x *Target) GetInit() int64 {
	if x != nil {
		return x.Init
	}
	return 0
}

func (x *Target) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *Target) GetSender() *NodeInfo {
	if x != nil {
		return x.Sender
	}
	return nil
}

type KBucket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        []*NodeInfo            `protobuf:"bytes,1,rep,name=Bucket,proto3" json:"Bucket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KBucket) Reset() {
	*x = KBucket{}
	mi := &file_kademlia_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KBucket) ProtoMessage() {}

func (x *KBucket) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KBucket.ProtoReflect.Descriptor instead.
func (*KBucket) Descriptor() ([]byte, []int) {
	return file_kademlia_proto_rawDescGZIP(), []int{5}
}

func (x *KBucket) GetBucket() []*NodeInfo {
	if x != nil {
		return x.Bucket
	}
	return nil
}

type FindValueResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	KNeartestBuckets *KBucket               `protobuf:"bytes,1,opt,name=KNeartestBuckets,proto3,oneof" json:"KNeartestBuckets,omitempty"`
	Value            *Data                  `protobuf:"bytes,2,opt,name=Value,proto3,oneof" json:"Value,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FindValueResponse) Reset() {
	*x = FindValueResponse{}
	mi := &file_kademlia_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindValueResponse) ProtoMessage() {}

func (x *FindValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindValueResponse.ProtoReflect.Descriptor instead.
func (*FindValueResponse) Descriptor() ([]byte, []int) {
	return file_kademlia_proto_rawDescGZIP(), []int{6}
}

func (x *FindValueResponse) GetKNeartestBuckets() *KBucket {
	if x != nil {
		return x.KNeartestBuckets
	}
	return nil
}

func (x *FindValueResponse) GetValue() *Data {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_kademlia_proto protoreflect.FileDescriptor

var file_kademlia_proto_rawDesc = string([]byte{
	0x0a, 0x0e, 0x6b, 0x61, 0x64, 0x65, 0x6d, 0x6c, 0x69, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x67, 0x6f, 0x64, 0x65, 0x6d, 0x6c, 0x69, 0x61, 0x22, 0x24, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x22, 0x3e, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x50, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x50, 0x12, 0x12, 0x0a, 0x04,
	0x50, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x6f, 0x72, 0x74,
	0x22, 0x44, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x6e, 0x69, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x45, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x45, 0x6e, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x42, 0x75, 0x66, 0x66, 0x65, 0x72, 0x22, 0x6f, 0x0a, 0x09, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x12, 0x2a, 0x0a, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x6f, 0x64, 0x65, 0x6d, 0x6c, 0x69, 0x61, 0x2e, 0x4e,
	0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12,
	0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x4b, 0x65,
	0x79, 0x12, 0x24, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x67, 0x6f, 0x64, 0x65, 0x6d, 0x6c, 0x69, 0x61, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x6a, 0x0a, 0x06, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x02, 0x49,
	0x44, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x6e, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x49, 0x6e, 0x69, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x45, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x03, 0x45, 0x6e, 0x64, 0x12, 0x2a, 0x0a, 0x06, 0x53, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x6f, 0x64, 0x65, 0x6d, 0x6c,
	0x69, 0x61, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x53, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x22, 0x35, 0x0a, 0x07, 0x4b, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x2a,
	0x0a, 0x06, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x67, 0x6f, 0x64, 0x65, 0x6d, 0x6c, 0x69, 0x61, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x06, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x22, 0xa1, 0x01, 0x0a, 0x11, 0x46,
	0x69, 0x6e, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x42, 0x0a, 0x10, 0x4b, 0x4e, 0x65, 0x61, 0x72, 0x74, 0x65, 0x73, 0x74, 0x42, 0x75, 0x63,
	0x6b, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x67, 0x6f, 0x64,
	0x65, 0x6d, 0x6c, 0x69, 0x61, 0x2e, 0x4b, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x00, 0x52,
	0x10, 0x4b, 0x4e, 0x65, 0x61, 0x72, 0x74, 0x65, 0x73, 0x74, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74,
	0x73, 0x88, 0x01, 0x01, 0x12, 0x29, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x67, 0x6f, 0x64, 0x65, 0x6d, 0x6c, 0x69, 0x61, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x48, 0x01, 0x52, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x88, 0x01, 0x01, 0x42,
	0x13, 0x0a, 0x11, 0x5f, 0x4b, 0x4e, 0x65, 0x61, 0x72, 0x74, 0x65, 0x73, 0x74, 0x42, 0x75, 0x63,
	0x6b, 0x65, 0x74, 0x73, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x32, 0xe1,
	0x01, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x30, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67, 0x12,
	0x12, 0x2e, 0x67, 0x6f, 0x64, 0x65, 0x6d, 0x6c, 0x69, 0x61, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49,
	0x6e, 0x66, 0x6f, 0x1a, 0x12, 0x2e, 0x67, 0x6f, 0x64, 0x65, 0x6d, 0x6c, 0x69, 0x61, 0x2e, 0x4e,
	0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x05, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x12, 0x13, 0x2e, 0x67, 0x6f, 0x64, 0x65, 0x6d, 0x6c, 0x69, 0x61, 0x2e, 0x53, 0x74,
	0x6f, 0x72, 0x65, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x12, 0x2e, 0x67, 0x6f, 0x64, 0x65, 0x6d, 0x6c,
	0x69, 0x61, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x12,
	0x31, 0x0a, 0x08, 0x46, 0x69, 0x6e, 0x64, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x2e, 0x67, 0x6f,
	0x64, 0x65, 0x6d, 0x6c, 0x69, 0x61, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x1a, 0x11, 0x2e,
	0x67, 0x6f, 0x64, 0x65, 0x6d, 0x6c, 0x69, 0x61, 0x2e, 0x4b, 0x42, 0x75, 0x63, 0x6b, 0x65, 0x74,
	0x22, 0x00, 0x12, 0x3e, 0x0a, 0x09, 0x46, 0x69, 0x6e, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x10, 0x2e, 0x67, 0x6f, 0x64, 0x65, 0x6d, 0x6c, 0x69, 0x61, 0x2e, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x1a, 0x1b, 0x2e, 0x67, 0x6f, 0x64, 0x65, 0x6d, 0x6c, 0x69, 0x61, 0x2e, 0x46, 0x69, 0x6e,
	0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x30, 0x01, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6a, 0x61, 0x63, 0x6b, 0x76, 0x65, 0x72, 0x6e, 0x65, 0x64, 0x61, 0x2f, 0x67, 0x6f, 0x64,
	0x65, 0x6d, 0x6c, 0x69, 0x61, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_kademlia_proto_rawDescOnce sync.Once
	file_kademlia_proto_rawDescData []byte
)

func file_kademlia_proto_rawDescGZIP() []byte {
	file_kademlia_proto_rawDescOnce.Do(func() {
		file_kademlia_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kademlia_proto_rawDesc), len(file_kademlia_proto_rawDesc)))
	})
	return file_kademlia_proto_rawDescData
}

var file_kademlia_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_kademlia_proto_goTypes = []any{
	(*Response)(nil),          // 0: godemlia.Response
	(*NodeInfo)(nil),          // 1: godemlia.NodeInfo
	(*Data)(nil),              // 2: godemlia.Data
	(*StoreData)(nil),         // 3: godemlia.StoreData
	(*Target)(nil),            // 4: godemlia.Target
	(*KBucket)(nil),           // 5: godemlia.KBucket
	(*FindValueResponse)(nil), // 6: godemlia.FindValueResponse
}
var file_kademlia_proto_depIdxs = []int32{
	1,  // 0: godemlia.StoreData.Sender:type_name -> godemlia.NodeInfo
	2,  // 1: godemlia.StoreData.Value:type_name -> godemlia.Data
	1,  // 2: godemlia.Target.Sender:type_name -> godemlia.NodeInfo
	1,  // 3: godemlia.KBucket.Bucket:type_name -> godemlia.NodeInfo
	5,  // 4: godemlia.FindValueResponse.KNeartestBuckets:type_name -> godemlia.KBucket
	2,  // 5: godemlia.FindValueResponse.Value:type_name -> godemlia.Data
	1,  // 6: godemlia.Node.Ping:input_type -> godemlia.NodeInfo
	3,  // 7: godemlia.Node.Store:input_type -> godemlia.StoreData
	4,  // 8: godemlia.Node.FindNode:input_type -> godemlia.Target
	4,  // 9: godemlia.Node.FindValue:input_type -> godemlia.Target
	1,  // 10: godemlia.Node.Ping:output_type -> godemlia.NodeInfo
	0,  // 11: godemlia.Node.Store:output_type -> godemlia.Response
	5,  // 12: godemlia.Node.FindNode:output_type -> godemlia.KBucket
	6,  // 13: godemlia.Node.FindValue:output_type -> godemlia.FindValueResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_kademlia_proto_init() }
func file_kademlia_proto_init() {
	if File_kademlia_proto != nil {
		return
	}
	file_kademlia_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kademlia_proto_rawDesc), len(file_kademlia_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kademlia_proto_goTypes,
		DependencyIndexes: file_kademlia_proto_depIdxs,
		MessageInfos:      file_kademlia_proto_msgTypes,
	}.Build()
	File_kademlia_proto = out.File
	file_kademlia_proto_goTypes = nil
	file_kademlia_proto_depIdxs = nil
}
